update LDAP_MATCHING_RULE set ROLES_LIST = (SELECT ';' + r.name
      FROM LDAP_MATCHING_RULE_ROLE_LINK AS mrl
      INNER JOIN SEC_ROLE r on r.id = mrl.ROLE_ID
      WHERE mrl.MATCHING_RULE_ID = LDAP_MATCHING_RULE.id
      FOR XML PATH(''))
