-- begin LDAP_MATCHING_RULE
alter table LDAP_MATCHING_RULE add constraint FK_LDAP_MATCHING_RULE_ACCESS_GROUP foreign key (ACCESS_GROUP_ID) references SEC_GROUP(ID)^
create index IDX_LDAP_MATCHING_RULE_ACCESS_GROUP on LDAP_MATCHING_RULE (ACCESS_GROUP_ID)^
-- end LDAP_MATCHING_RULE
-- begin LDAP_MATCHING_RULE_ROLE_LINK
alter table LDAP_MATCHING_RULE_ROLE_LINK add constraint FK_MATRULROL_MATCHING_RULE foreign key (MATCHING_RULE_ID) references LDAP_MATCHING_RULE(ID)^
alter table LDAP_MATCHING_RULE_ROLE_LINK add constraint FK_MATRULROL_ROLE foreign key (ROLE_ID) references SEC_ROLE(ID)^
-- end LDAP_MATCHING_RULE_ROLE_LINK
